version: '3.8'
services:
  db:
    image: phidata/pgvector:16
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: postgresql://ai:ai@db:5432/ai
    depends_on:
      - db
    volumes:
      - ./knowledge_files:/app/application_materials/knowledge_files  # Mount host directory
    network_mode: "host"
volumes:
  pgvolume:
